### ISSUE TITLE
Is this related to songsheetapp?

### ISSUE THREAD

**Issue by nsndvd** [jannessm/songsheet-app#11]
Hi, sorry I write an issue but I couldn't find a different way to contact you.

I recently started using songsheet and I wonder to what point your project is related to that application. Can you very shortly elaborate?
http://songsheetapp.com/

**Comment by jannessm** [comment]
Sadly this isnt related to the app. It is just a private project which has the same name. It is not finished yet but is focusing on the usage at pc, Mac or linux. And of course it will be open source. The main functionality will cover a very easy way to notate song for bands and present them via a wireless network to each device with a browser. One person can them scroll for the whole band so that all are staying where they have to be. When it is ready for usage it would be an honor to me if you would test it. How you can edit the songs you can see at my project SongSheet.

**Comment by nsndvd** [comment]
Thanks for your reply, it's a very interesting project even if not exactly what I was looking for. Anyway I'll sure be happy to try it out

**Comment by nilsroesel** [comment]
I think @jannessm would also be open for feature requests. atm it covers mainly our demands, but hey, there is at least always room for ideas

**Comment by nsndvd** [comment]
My current situation: I have to use songsheetapp sheets and, to my understanding, I can use an iOS app or a Windows app. Unfortunately I have an Android phone and a Macbook.

So I would probably still be interested in contributing to this project if the sheet format was compatible. Which is actually a good question.. Can you tell me if the sheet format is compatible?

**Comment by nilsroesel** [comment]
unfortunately it looks like incompatible. we use some markdownish syntax.
Maybe we can provide a migration tool in future, when we have a stable build

**Comment by nsndvd** [comment]
Too bad.. We need the ISO guys to create a standard for song sheets

**Comment by nilsroesel** [comment]
Indeed :D
but as far as i can say:
https://dsbsoft.com/
this tool looks like as it has a quite similar syntax. if the songsheetapp guys are using the same its migratable i think.

**Comment by nsndvd** [comment]
Yeah unfortunately I can't find a specification for the syntax. I'll try to go deeper in some of the sheets I have and see if there are potential issues

**Comment by nilsroesel** [comment]
I think there will be a bunch of differences, but regarding to this second example application for windwos, it didnt looked unmigratable on the first look. If they use the same syntax in the background of their editor, i would say its migratable
